services:
  postgres:
    container_name: postgres_jobapp
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - backend
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_jobapp
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - backend
    restart: unless-stopped

#  config-server-ms:
#    image: dcode007/config-server-ms:latest
#    container_name: config-server-ms
#    ports:
#      - 8080:8080
#    depends_on:
#      - servicereg
#    networks:
#      - microservice-network
#      - backend
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - JAVA_TOOL_OPTIONS=-Xms64m -Xmx512m -XX:+UseSerialGC -XX:MaxMetaspaceSize=192m
#
#  servicereg:
#    image: dcode007/servicereg:latest
#    container_name: servicereg
#    ports:
#      - "8761:8761"
#    depends_on:
#      - rabbitmq
##      - zipkin
#      - postgres
##      - pgadmin
#    networks:
#      - microservice-network
#      - backend

#  companyms:
#    image: dcode007/companyms:latest
#    container_name: company
#    ports:
#      - 8081:8081
#    depends_on:
#      - servicereg
#      - config-server-ms
#    networks:
#      - microservice-network
#      - backend
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - JAVA_TOOL_OPTIONS=-Xms64m -Xmx512m -XX:+UseSerialGC -XX:MaxMetaspaceSize=192m
#
#  jobms:
#    image: dcode007/jobms:latest
#    container_name: job
#    ports:
#      - 8082:8082
#    depends_on:
#      - servicereg
#      - config-server-ms
#    networks:
#      - microservice-network
#      - backend
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicereg:8761/eureka
#      - JAVA_TOOL_OPTIONS=-Xms64m -Xmx512m -XX:+UseSerialGC -XX:MaxMetaspaceSize=192m
#
#  reviewms:
#    image: dcode007/reviewms:latest
#    container_name: review
#    ports:
#      - 8083:8083
#    depends_on:
#      - servicereg
#      - config-server-ms
#    networks:
#      - microservice-network
#      - backend
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - JAVA_TOOL_OPTIONS=-Xms64m -Xmx512m -XX:+UseSerialGC -XX:MaxMetaspaceSize=192m

  zipkin:
    image: openzipkin/zipkin
    mem_limit: 700m
    container_name: zipkin_jobapp
    ports:
      - "9411:9411"
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_jobapp
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - backend

#  gateway-ms:
#    image: dcode007/gateway-ms:latest
#    ports:
#      - 8084:8084
#    depends_on:
#      - servicereg
#    networks:
#      - microservice-network
#      - backend
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - JAVA_TOOL_OPTIONS=-Xms64m -Xmx512m -XX:+UseSerialGC -XX:MaxMetaspaceSize=192m


networks:
  microservice-network:
    driver: bridge
  backend:
    driver: bridge

volumes:
  postgres:
  pgadmin:

