spring:
  application:
    name: reviewms
  datasource:
    url: jdbc:postgresql://localhost:5433/review
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    database: PostgreSQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8083