spring:
  application:
    name: review-service
  datasource:
    url: jdbc:postgresql://localhost:5433/review
    username:
    password:
  jpa:
    database: PostgreSQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8083