spring:
  application:
    name: gateway
  config:
    import: optional:configserver://config-server-ms:8080
  cloud:
    gateway:
      routes:
        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/companies,/companies/**

        - id: job-service
          uri: lb://job-service
          predicates:
            - Path=/jobs,/jobs/**

        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/reviews,/reviews/**

        - id: eureka-server
          uri: http://servicereg:8761
          predicates:
            - Path=/eureka/main
          filters:
            - SetPath=/

        - id: eureka-server-static
          uri: http://servicereg:8761
          predicates:
            - Path=/eureka/**

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://servicereg:8761/eureka/